Repository fragjulian/ASE-WS22-MazeRunner, pull requests merged in 2022-12, with the labels that each got.

#18 Frontend v2
  frontend/.editorconfig
  frontend/.gitignore
  frontend/.vscode/extensions.json
  frontend/.vscode/launch.json
  frontend/.vscode/tasks.json
  frontend/README.md
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/assets/.gitkeep
  frontend/src/favicon.ico
  frontend/src/index.html
  frontend/src/main.ts
  frontend/src/styles.css
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.spec.json
Labels: Initial Project

#19 implement basic webpage
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/navbar/mr-navbar.component.css
  frontend/src/app/navbar/mr-navbar.component.html
  frontend/src/app/navbar/mr-navbar.component.spec.ts
  frontend/src/app/navbar/mr-navbar.component.ts
  frontend/src/app/upload/mr-upload-file.component.css
  frontend/src/app/upload/mr-upload-file.component.html
  frontend/src/app/upload/mr-upload-file.component.spec.ts
  frontend/src/app/upload/mr-upload-file.component.ts
  frontend/src/assets/logo.png
  frontend/src/favicon.ico
  frontend/src/index.html
  frontend/src/styles.css
  frontend/tsconfig.json
Labels: enhancement

#27 Frontend v3
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/about/about.component.css
  frontend/src/app/about/about.component.html
  frontend/src/app/about/about.component.spec.ts
  frontend/src/app/about/about.component.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.css
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.module.ts
  frontend/src/app/footer/footer.component.css
  frontend/src/app/footer/footer.component.html
  frontend/src/app/footer/footer.component.spec.ts
  frontend/src/app/footer/footer.component.ts
  frontend/src/app/navbar/mr-navbar.component.css
  frontend/src/app/navbar/mr-navbar.component.html
  frontend/src/app/navbar/mr-navbar.component.ts
  frontend/src/app/navbar/navbar.component.css
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/navbar/navbar.component.spec.ts
  frontend/src/app/navbar/navbar.component.ts
  frontend/src/index.html
  frontend/src/styles.css
Labels: enhancement

#30 First working maze solver backend
  backend/pom.xml
  backend/src/main/java/com/example/mazerunner/ColourWallDetector.java
  backend/src/main/java/com/example/mazerunner/DistanceMetric.java
  backend/src/main/java/com/example/mazerunner/EuclideanDistance.java
  backend/src/main/java/com/example/mazerunner/Maze.java
  backend/src/main/java/com/example/mazerunner/MazeRunnerApplication.java
  backend/src/main/java/com/example/mazerunner/MazeSolverController.java
  backend/src/main/java/com/example/mazerunner/Position.java
  backend/src/main/java/com/example/mazerunner/WallDetector.java
Labels: enhancement

#39 Create acceptance.yml
  .github/workflows/acceptance.yml
Labels: enhancement, Initial Project

#43 Added selenium directory for UI tests using Selenium and Maven
  selenium/.gitignore
  selenium/pom.xml
  selenium/src/main/java/org/example/App.java
  selenium/src/test/java/org/example/UITest.java
Labels: enhancement

#44 first basic UI tests
  frontend/src/app/footer/footer.component.html
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/upload/mr-upload-file.component.html
  selenium/pom.xml
  selenium/src/main/java/at/stulpinger/ase/App.java
  selenium/src/test/java/at/stulpinger/ase/UITest.java
  selenium/src/test/java/at/stulpinger/ase/WebApp.java
  selenium/src/test/java/org/example/UITest.java
Labels: QA

#50 CI-CD workflow for Selenium UI tests
  .github/workflows/acceptance.yml
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  backend/Dockerfile
  backend/src/main/resources/application.properties
  selenium/pom.xml
Labels: enhancement, QA

#54 FE fixed Issue#51
  .github/workflows/acceptance.yml
  .github/workflows/build-test.yml
  frontend/Dockerfile
  frontend/nginx.conf
  selenium/src/test/java/at/stulpinger/ase/UITest.java
Labels: bug
