Repository fragjulian/ASE-WS22-MazeRunner, pull requests merged in 2023-01, with the labels that each got.

#53 Fe rest
  backend/src/main/java/com/example/mazerunner/MazeSolverController.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/about/about.component.html
  frontend/src/app/about/about.component.spec.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/colorpicker/colorpicker.component.css
  frontend/src/app/colorpicker/colorpicker.component.html
  frontend/src/app/colorpicker/colorpicker.component.spec.ts
  frontend/src/app/colorpicker/colorpicker.component.ts
  frontend/src/app/footer/footer.component.html
  frontend/src/app/footer/footer.component.spec.ts
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/navbar/navbar.component.spec.ts
  frontend/src/app/rest-upload/rest-upload.component.css
  frontend/src/app/rest-upload/rest-upload.component.html
  frontend/src/app/rest-upload/rest-upload.component.spec.ts
  frontend/src/app/rest-upload/rest-upload.component.ts
  frontend/src/app/upload/mr-upload-file.component.css
  frontend/src/app/upload/mr-upload-file.component.html
  frontend/src/app/upload/mr-upload-file.component.spec.ts
  frontend/src/app/upload/mr-upload-file.component.ts
  selenium/src/test/java/at/stulpinger/ase/UITest.java
Labels: enhancement

#56 implement maze builder
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.module.ts
  frontend/src/app/maze-builder/maze-builder.component.css
  frontend/src/app/maze-builder/maze-builder.component.html
  frontend/src/app/maze-builder/maze-builder.component.spec.ts
  frontend/src/app/maze-builder/maze-builder.component.ts
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/navbar/navbar.component.spec.ts
  frontend/src/app/rest-upload/rest-upload.component.css
Labels: enhancement

#67 CI-CD-Sonar fixed Issue#62
  .github/workflows/acceptance.yml
  README.md
  backend/pom.xml
  frontend/sonar-project.properties
  selenium/pom.xml
Labels: bug, QA

#68 CI-CD-Sonar fixed Issue#62 again
  .github/workflows/acceptance.yml
  backend/pom.xml
Labels: bug, QA

#69 JMeter, CI-CD-JMeter, workflow cleanup
  .github/workflows/acceptance.yml
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  README.md
  backend/pom.xml
  frontend/karma.conf.js
  frontend/package-lock.json
  frontend/package.json
  jmeter/jmeter/mazes/maze1.png
  jmeter/jmeter/mazes/maze2.png
  jmeter/jmeter/mazes/maze3.png
  jmeter/jmeter/mazes/maze4.png
  jmeter/jmeter/mazes/maze5.png
  jmeter/jmeter/tests_CI_CD/test_2k_maze.jmx
  jmeter/jmeter/tests_CI_CD/test_basic.jmx
  jmeter/jmeter/tests_CI_CD/test_complex_maze.jmx
  jmeter/jmeter/tests_CI_CD/test_maze_from_builder.jmx
  jmeter/jmeter/tests_local/test_2k_maze.jmx
  jmeter/jmeter/tests_local/test_basic.jmx
  jmeter/jmeter/tests_local/test_complex_maze.jmx
  jmeter/jmeter/tests_local/test_maze_from_builder.jmx
  jmeter/pom.xml
Labels: enhancement, QA

#72 CI-Cd Fixed Issue#71
  .github/workflows/deploy.yml
Labels: bug, QA

#58 Fe optimization
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/about/about.component.css
  frontend/src/app/about/about.component.html
  frontend/src/app/app.module.ts
  frontend/src/app/colorpicker/colorpicker.component.css
  frontend/src/app/colorpicker/colorpicker.component.html
  frontend/src/app/colorpicker/colorpicker.component.spec.ts
  frontend/src/app/colorpicker/colorpicker.component.ts
  frontend/src/app/footer/footer.component.html
  frontend/src/app/maze-builder/maze-builder.component.html
  frontend/src/app/maze-builder/maze-builder.component.spec.ts
  frontend/src/app/maze-builder/maze-builder.component.ts
  frontend/src/app/navbar/navbar.component.css
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/navbar/navbar.component.spec.ts
  frontend/src/app/rest-upload/Services/download-image.service.spec.ts
  frontend/src/app/rest-upload/Services/download-image.service.ts
  frontend/src/app/rest-upload/Services/rest.service.spec.ts
  frontend/src/app/rest-upload/Services/rest.service.ts
  frontend/src/app/rest-upload/rest-upload.component.css
  frontend/src/app/rest-upload/rest-upload.component.html
  frontend/src/app/rest-upload/rest-upload.component.spec.ts
  frontend/src/app/rest-upload/rest-upload.component.ts
  frontend/src/index.html
  frontend/src/main.ts
  frontend/src/styles.css
Labels: enhancement

#70 Maze solver auto solve
  backend/pom.xml
  backend/src/main/java/com/example/mazerunner/ColorWallDetector.java
  backend/src/main/java/com/example/mazerunner/DepthFirst.java
  backend/src/main/java/com/example/mazerunner/EuclideanDistance.java
  backend/src/main/java/com/example/mazerunner/JsonWallDetector.java
  backend/src/main/java/com/example/mazerunner/Maze.java
  backend/src/main/java/com/example/mazerunner/MazeParameterBuilder.java
  backend/src/main/java/com/example/mazerunner/MazeRunnerApplication.java
  backend/src/main/java/com/example/mazerunner/MazeSolverController.java
  backend/src/main/java/com/example/mazerunner/MazeUtilsFactory.java
  backend/src/main/java/com/example/mazerunner/Path.java
  backend/src/main/java/com/example/mazerunner/PositionDetectorColor.java
  backend/src/main/java/com/example/mazerunner/SearchStrategy.java
  backend/src/main/java/com/example/mazerunner/SquareDistance.java
  backend/src/main/java/com/example/mazerunner/WallDetector.java
  backend/src/test/java/com/example/mazerunner/ColorWallDetectorTest.java
  backend/src/test/java/com/example/mazerunner/EdgeDetectionWallDetectionTest.java
  backend/src/test/java/com/example/mazerunner/PositionDetectorColorTest.java
  backend/src/test/java/com/example/mazerunner/SquareDistanceTest.java
  doc/backend/allowed_file_types
  frontend/package-lock.json
  frontend/src/app/Position.ts
  frontend/src/app/app.module.ts
  frontend/src/app/maze-builder-auto-solve.service.spec.ts
  frontend/src/app/maze-builder-auto-solve.service.ts
  frontend/src/app/maze-builder/maze-builder.component.css
  frontend/src/app/maze-builder/maze-builder.component.html
  frontend/src/app/maze-builder/maze-builder.component.spec.ts
  frontend/src/app/maze-builder/maze-builder.component.ts
  frontend/src/app/rest-upload/Services/rest.service.spec.ts
  frontend/src/app/rest-upload/Services/rest.service.ts
  frontend/src/assets/bin.png
  frontend/src/assets/goal.png
  frontend/src/assets/obstacle.png
  frontend/src/assets/start.png
  frontend/src/assets/wall.png
  jmeter/jmeter/tests_CI_CD/test_2k_maze.jmx
  jmeter/jmeter/tests_CI_CD/test_basic.jmx
  jmeter/jmeter/tests_CI_CD/test_complex_maze.jmx
  jmeter/jmeter/tests_CI_CD/test_maze_from_builder.jmx
  jmeter/jmeter/tests_local/test_2k_maze.jmx
  jmeter/jmeter/tests_local/test_basic.jmx
  jmeter/jmeter/tests_local/test_complex_maze.jmx
  jmeter/jmeter/tests_local/test_maze_from_builder.jmx
Labels: enhancement

#81 add UI tests for maze builder feature
  frontend/src/app/about/about.component.html
  frontend/src/app/maze-builder/maze-builder.component.css
  frontend/src/app/maze-builder/maze-builder.component.html
  frontend/src/app/maze-builder/maze-builder.component.ts
  selenium/src/test/java/at/stulpinger/ase/Canvas.java
  selenium/src/test/java/at/stulpinger/ase/Color.java
  selenium/src/test/java/at/stulpinger/ase/FileUtil.java
  selenium/src/test/java/at/stulpinger/ase/Line.java
  selenium/src/test/java/at/stulpinger/ase/Page.java
  selenium/src/test/java/at/stulpinger/ase/UITest.java
  selenium/src/test/java/at/stulpinger/ase/WebApp.java
  selenium/src/test/resources/black-border.png
  selenium/src/test/resources/empty-maze.png
  selenium/src/test/resources/green-border.png
  selenium/src/test/resources/red-border.png
  selenium/src/test/resources/solved-maze-no-walls.png
  selenium/src/test/resources/solved-maze-simple-walls.png
  selenium/src/test/resources/star-shape.png
  selenium/src/test/resources/three-pixels.png
Labels: QA

#83 FE Issue#80, Issue#57
  frontend/angular.json
  frontend/src/app/about/about.component.css
  frontend/src/app/colorpicker/colorpicker.component.css
  frontend/src/app/maze-builder-auto-solve.service.ts
  frontend/src/app/navbar/navbar.component.css
  frontend/src/app/navbar/navbar.component.html
  frontend/src/app/navbar/navbar.component.spec.ts
  frontend/src/app/rest-upload/Services/rest.service.ts
  frontend/src/app/rest-upload/rest-upload.component.css
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
Labels: bug, enhancement

#84 fix UI test port
  selenium/src/test/java/at/stulpinger/ase/UITest.java
Labels: bug

#85 Additional JMeter tests for JSON endpoint
  jmeter/jmeter/tests_CI_CD/test_path_endpoint.jmx
  jmeter/jmeter/tests_local/test_path_endpoint.jmx
Labels: QA
